############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Events"
url = "/event"
weight = 2

[[main]]
name = "Photos"
url = "/photos"
weight = 3

[[main]]
name = "Team"
url = "/team"
weight = 4

[[main]]
name = "Contact"
url = "/contact"
weight = 5


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Mentions légales "
url = "/mentions-legales "
weight = 2




