############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Activities"
url = "/activities"
weight = 2


[[main]]
name = "Seminar and Group"
url = "/seminar_and_group"
weight = 4


[[main]]
name = "News"
url = "/news"
weight = 3

[[main]]
name = "Practical information"
url = "/practical_information"
weight = 5


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Mentions légales "
url = "/mentions-legales "
weight = 2

# drop down for activities
[[main]]
parent = "Activities"
name = "Norma Loops"
url = "activities/norma_loops"
weight = 1

[[main]]
parent = "Activities"
name = "Norma Zen"
url = "activities/norma_zen"
weight = 2

[[main]]
parent = "Activities"
name = "Norma Kids"
url = "activities/norma_kids"
weight = 3

[[main]]
parent = "Activities"
name = "Baignade"
url = "activities/baignade"
weight = 4

[[main]]
parent = "Activities"
name = "Tennis"
url = "activities/tennis"
weight = 5

[[main]]
parent = "Activities"
name = "Cinéma"
url = "activities/cinema"
weight = 6




