backend:
  name: git-gateway
  repo: Vexflip/website-la-norma
  branch: main
  identity_url: https://auth.decapbridge.com/sites/0f527a0d-527c-4363-99aa-75cb7c8d0656
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: https://vexflip.github.io

media_folder: static/images
public_folder: /images

collections:
  - name: 'news'
    label: 'News'
    folder: 'content/news'
    create: true
    editor:
      preview: false
    fields:
      - label: "Event"
        name: "event"
        widget: "object"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Starting Date", name: "date_start", widget: "datetime" }
          - { label: "Ending Date", name: "date_end", widget: "datetime" }
          - { label: "Description", name: "description", widget: "markdown" }
          - { label: "Main Image", name: "image", widget: "image" }
          - { label: "Logo", name: "logo", widget: "image" }
          - label: "Gallery"
            name: "gallery"
            widget: "list"
            field: { label: "Image", name: "image", widget: "image" }
          - label: "Tags"
            name: "tags"
            widget: "select"
            options:
              - Event
              - Kids
              - Adventure
              - Family