backend:
  name: git-gateway
  repo: Vexflip/website-la-norma
  branch: main
  identity_url: https://auth.decapbridge.com/sites/0f527a0d-527c-4363-99aa-75cb7c8d0656
  gateway_url: https://gateway.decapbridge.com

  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: "-"

logo_url: https://decapbridge.com/decapcms-with-bridge.svg
site_url: https://vexflip.github.io

media_folder: static/images  # Dossier local où sont stockés les médias téléchargés
public_folder: /images       # Chemin URL pour accéder aux médias téléchargés

collections:
  - name: activities
    label: Activités
    folder: content/english/activities
    create: true
    slug: "{{fields.activity.name}}"
    summary: "{{fields.activity.name}}"
    exclude: _index.md
    editor:
      preview: false
    fields:
      - label: Activité
        name: activity
        widget: object
        fields:
          - { label: Nom, name: name, widget: string, required: true, hint: "Entrez le nom de l’activité, par ex. « Norma Loops »" }
          - { label: Description, name: description, widget: text, required: true, hint: "Description expliquant le contenu de l’activité." }

          - label: Horaire
            name: horaire
            widget: list
            hint: "Listez les plages horaires et les jours où l’activité est disponible."
            fields:
              - { label: Plage, name: window, widget: string, hint: "Période concernée, ex : « Du 24 Décembre 2025 au 24 Août 2025  »" }
              - label: Entrées
                name: entries
                widget: list
                hint: "Précisez les jours de la semaine et les horaires correspondants."
                fields:
                  - { label: Jour, name: day, widget: select, options: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"], hint: "Choisissez le jour de la semaine." }
                  - { label: Heures, name: hours, widget: string, hint: "Indiquez les heures pour ce jour, ex : « 09:00 - 17:00 »" }

          - label: Notifications
            name: notifications
            widget: list
            summary: "{{fields.title}} ({{fields.type}})"
            hint: "Ajoutez des notifications importantes liées à cette activité."
            fields:
              - { label: Titre, name: title, widget: string, required: true, hint: "Titre court de la notification." }
              - label: Type
                name: type
                widget: select
                options:
                  - { label: Attention, value: attention }
                  - { label: Avertissement, value: warning }
                  - { label: Succès, value: success }
                  - { label: Info, value: info }
                  - { label: Remarque, value: remark }
                default: info
                required: true
                hint: "Choisissez la catégorie pour distinguer visuellement le message."
              - { label: Contenu, name: content, widget: markdown, required: true, hint: "Message détaillé de la notification" }

          - { label: Image, name: image, widget: image, hint: "Téléchargez une image principale représentant l’activité." }
          - { label: Logo, name: logo, widget: image, hint: "Téléchargez un logo lié à l’activité." }
          - label: Gallery
            name: gallery
            widget: gallery-upload
            required: false
            summary: "{{fields.image}}"
            media_folder: "static/images/activities/{{slug}}/{{slug}}-gallery"
            public_folder: "/images/activities/{{slug}}/{{slug}}-gallery"
            hint: "Ajoutez plusieurs images pour la galerie."
  

          - { label: Action du formulaire de contact, name: contact_form_action, widget: string, required: false, hint: "Addresse mail : ex : « joesph@gmail.com »" }

          - label: OpenStreetMap
            name: openstreet_map
            widget: object
            hint: "Activez et configurez la localisation sur la carte pour cette activité."
            fields:
              - { label: Activer, name: enable, widget: boolean, default: false, hint: "Cochez pour afficher la carte sur la page de l’activité." }
              - { label: Latitude, name: latitude, widget: number, value_type: float, step: 0.0000001, required: false, hint: "Coordonnée latitude, ex : 46.8139" }
              - { label: Longitude, name: longitude, widget: number, value_type: float, step: 0.0000001, required: false, hint: "Coordonnée longitude, ex : -71.2080" }
              - { label: Zoom, name: zoom, widget: number, value_type: int, default: 15, required: false, hint: "Niveau de zoom sur la carte (1 = monde, 20 = niveau rue)." }

  - name: news
    label: Actualités
    folder: content/english/news
    create: true
    slug: "{{fields.event.date_start | date('yyyy-MM-dd')}}-{{fields.event.name | slug}}"
    filename: "{{fields.event.name | slug}}-{{fields.event.date_start | date('yyyy-MM-dd')}}"
    summary: "{{fields.event.name}}"
    ignore: {field: "NoCMS", value: true}
    editor:
      preview: false
    fields:
      - label: Événement
        name: event
        widget: object
        hint: "Renseignez les détails concernant l’actualité."
        fields:
          - { label: Nom, name: name, widget: string, required: true, hint: "Nom de l’événement, ex. « Festival d’été 2025 »." }
          - { label: Date de début, name: date_start, widget: datetime, required: true, hint: "Date et heure de début de l’événement. (Si pas d'heure specifique mettre 00:00)" }
          - { label: Date de fin, name: date_end, widget: datetime, required: false, hint: "Optionnel : date et heure de fin de l’événement. (Si pas d'heure specifique mettre 00:00)" }
          - { label: Description, name: description, widget: markdown, required: true, hint: "Description détaillée de l’événement." }
          - { label: Image principale, name: image, widget: image, required: false, hint: "Image principale de l’événement." }
          - { label: Logo, name: logo, widget: image, required: false, hint: "Logo optionnel de l’événement." }
          - label: "Galérie"
            required: false
            name: gallery-image
            widget: "list"
            hint: "Ajoutez plusieurs images pour la galérie."
            fields:
              - label: "Image"
                name: "image"
                widget: "image"
                media_folder: "static/images/event/{{fields.event.name}}/{{fields.event.name}}-gallery"
                public_folder: "/images/event/{{fields.event.name}}/{{fields.event.name}}-gallery"
          - label: Galerie Url
            name: gallery
            widget: hidden
            default: "/images/event/{{fields.event.name}}/{{fields.event.name}}-gallery"
          - label: Tags
            name: tags
            widget: select
            multiple: true
            options:
              - Événement
              - Enfants
              - Aventure
              - Famille
            hint: "Sélectionnez les tags correspondant pour catégoriser l’événement."

  - name: tickets
    label: Billets
    folder: content/english/tickets
    create: true
    slug: "{{fields.title | slug}}-{{fields.id}}"
    filename: "{{fields.title | slug}}-{{fields.id}}"
    summary: "{{fields.title}}"
    editor:
      preview: false
    fields:
      - { label: Titre, name: title, widget: string, required: true, hint: "Nom du type de billet." }
      - { label: ID, name: id, widget: string, required: true, hint: "Identifiant unique pour ce billet." }
      - label: "Groupe"
        name: "group"
        widget: "relation"
        collection: "activities"
        search_fields: ["activity.name"]
        value_field: "activity.name"
        display_fields: ["activity.name"]
        required: true
        hint: "Activité auquel appartient ce billet." 
      - { label: Prix, name: price, widget: number, required: true, hint: "Prix du billet dans votre devise." }
      - { label: Informations, name: info, widget: text, required: false, hint: "Informations supplémentaires ou conditions relatives au billet." }