backend:
  name: git-gateway
  repo: Vexflip/website-la-norma
  branch: main
  identity_url: https://auth.decapbridge.com/sites/0f527a0d-527c-4363-99aa-75cb7c8d0656
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{  author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: https://vexflip.github.io

media_folder: static/images
public_folder: /images


collections:
  - name: "activities"
    label: "Activities"
    folder: "content/english/activities"
    create: true
    slug: "{{fields.activity.name}}"
    summary: "{{fields.activity.name}}"
    exclude: "_index.md"
    editor:
      preview: false
    fields:
      - label: "Activity"
        name: "activity"
        widget: "object"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }

          - label: "Horaire"
            name: "horaire"
            widget: "list"
            fields:
              - { label: "Window", name: "window", widget: "string", hint: "Ex: 27.05.2025 - 18.08.2025" }
              - label: "Entries"
                name: "entries"
                widget: "list"
                fields:
                  - { label: "Day", name: "day", widget: "select", options: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"] }
                  - { label: "Hours", name: "hours", widget: "string" }

          - label: "Notifications"
            name: "notifications"
            widget: "list"
            summary: "{{fields.title}} ({{fields.type}})"
            fields:
              - { label: "Title", name: "title", widget: "string", required: true }
              - label: "Type"
                name: "type"
                widget: "select"
                options:
                  - { label: "Attention", value: "attention" }
                  - { label: "Warning", value: "warning" }
                  - { label: "Success", value: "success" }
                  - { label: "Info", value: "info" }
                  - { label: "Remark", value: "remark" }
                default: "info"
                required: true
              - { label: "Content", name: "content", widget: "markdown", required: true }

          - { label: "Image", name: "image", widget: "image" }
          - { label: "Logo", name: "logo", widget: "image" }
          - { label: "Gallery", name: "gallery", widget: "string" }
          - { label: "Contact Form Action", name: "contact_form_action", widget: "string", required: false }

          - label: "OpenStreetMap"
            name: "openstreet_map"
            widget: "object"
            fields:
              - { label: "Enable", name: "enable", widget: "boolean", default: false }
              - { label: "Latitude", name: "latitude", widget: "number", value_type: "float", step: 0.0000001 }
              - { label: "Longitude", name: "longitude", widget: "number", value_type: "float", step: 0.0000001 }
              - { label: "Zoom", name: "zoom", widget: "number", value_type: "int", default: 15 }


  - name: 'news'
    label: 'News'
    folder: 'content/english/news'
    create: true
    slug: "{{date_start}}-{{fields.event.name}}"
    summary: "{{fields.event.name}}"
    filename: "{{fields.event.name}}-{{fields.event.date_start}}"
    editor:
      preview: false
    exclude: "_index.md"
    fields:
      - label: "Event"
        name: "event"
        widget: "object"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Starting Date", name: "date_start", widget: "datetime" }
          - { label: "Ending Date", name: "date_end", widget: "datetime" }
          - { label: "Description", name: "description", widget: "markdown" }
          - { label: "Main Image", name: "image", widget: "image" }
          - { label: "Logo", name: "logo", widget: "image" }
          - label: "Gallery"
            name: "gallery"
            widget: "list"
            field: { label: "Image", name: "image", widget: "image" }
          - label: "Tags"
            name: "tags"
            multiple: true
            widget: "select"
            options:
              - Event
              - Kids
              - Adventure
              - Family


  - name: "tickets"
    label: "Tickets"
    folder: "content/english/tickets"
    slug: "{{fields.title}}-{{fields.id}}"
    summary: "{{fields.title}}"
    filename: "{{fields.title}}-{{fields.id}}"
    create: true
    editor:
      preview: false
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "id", label: "ID", widget: "string"}
      - { name: "group", label: "Group", widget: "string" }
      - { name: "price", label: "Price", widget: "number" }
      - { name: "info", label: "Info", widget: "text" }

